test_infra.py: Fix stdout patching
After a flake8 patch[0], the current way of patching stdout breaks with:

>  AttributeError: '_io.StringIO' object has no attribute 'buffer'

0_ https://github.com/PyCQA/flake8/commit/7a353d2e23ed336cea41a05a03732a35e45801c2